apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "13"
    description: marketing-box-frontend
  labels:
    app: marketing-box-frontend
    environment: Development
    tier: Service
  name: marketing-box-frontend
  namespace: marketing-box
spec:
  minReadySeconds: 10
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: marketing-box-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: marketing-box-frontend
      name: marketing-box-frontend
    spec:
      containers:
      - env:
#        - name: SETTINGS_URL
#          value: http://192.168.172.172:9897/MarketingBoxFrontend
        - name: ConsoleOutputLogLevel
          value: Information
        - name: ENV_INFO
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: mboxregistry.azurecr.io/marketingbox/marketingbox.frontend-test:latest
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - /bin/echo 'options single-request-reopen' >> /etc/resolv.conf
#         livenessProbe:
#           failureThreshold: 3
#           httpGet:
#             path: /api/isalive
#             port: 8080
#             scheme: HTTP
#           initialDelaySeconds: 20
#           periodSeconds: 20
#           successThreshold: 1
#           timeoutSeconds: 1
        name: marketing-box-frontend
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 80
          protocol: TCP
        - containerPort: 3000
          protocol: TCP
#         readinessProbe:
#           failureThreshold: 3
#           httpGet:
#             path: /api/isalive
#             port: 8080
#             scheme: HTTP
#           initialDelaySeconds: 10
#           periodSeconds: 5
#           successThreshold: 1
#           timeoutSeconds: 3
        resources:
          limits:
            cpu: 300m
            memory: 800Mi
          requests:
            cpu: 50m
            memory: 150Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: mbox
      nodeSelector:
        agentpool: marketingbox
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
