/**
 *  interface for Login Type
 */
export enum ForgetPwdTypes {
  FORGET_PASSWORD = "@@forget/FORGET_PASSWORD",
  FORGET_PASSWORD_SUCCESS = "@@forget/FORGET_PASSWORD_SUCCESS",
  FORGET_PASSWORD_ERROR = "@@forget/FORGET_PASSWORD_ERROR",

  RESET_PASSWORD = "@@forget/RESET_PASSWORD",
  RESET_PASSWORD_SUCCESS = "@@forget/RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_ERROR = "@@forget/RESET_PASSWORD_ERROR",


  CLEAR_STORE = "@@forget/clear-store",
}
