name: NodeJS with Webpack

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    #strategy:
    #  matrix:
    #    node-version: [12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      uses: vazco/github-actions-branch-name@v1
      id: branch

    - id: string
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ github.event.repository.name }}
        
    - name: Get current time
      uses: MyJetTools/get-current-time@v2
      id: current-time
      with:
        format: YYYY-MM-DD HH:mm:ss
        utcOffset: "+00:00"
        
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
    #    node-version: ${{ matrix.node-version }}
        node-version: 14.x

    - name: Install
      run: |
        npm install
    - name: Build
      run: |
        CI=false
        npm run build

    - name: Publish image github
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.MBOX_REGISTRY_USER }}
        password: ${{ secrets.MBOX_REGISTRY_PASS }}
        path: ./
        registry: ${{ secrets.MBOX_REGISTRY_URL }} 
        repository: marketingbox/${{ steps.string.outputs.lowercase }}-${{ steps.branch.outputs.branch_name }}
        tags: latest
        build_args: app_version=${{ steps.string.outputs.lowercase }}-${{ steps.branch.outputs.branch_name }}:latest,app_compilation_date=${{ steps.current-time.outputs.formattedTime }}

#     - name: executing remote ssh commands using password
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.USERNAME }}
#         port: ${{ secrets.PORT }}
#         key: ${{ secrets.PRIVATE_KEY }}
#         script: cd /home/monfex/Services/educationweb-test && docker-compose pull && docker-compose up -d
